# Generated by Django 4.0.2 on 2022-02-17 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.AddField(
            model_name='client',
            name='phoneNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('WD', 'Windsor'), ('TO', 'Toronto'), ('CH', 'Chatham'), ('WL', 'Waterloo')], default='CH', max_length=2),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfItems', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Cancelled'), ('1', 'Placed'), ('2', 'Shipped'), ('3', 'Delivered')], max_length=1)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientOrderedItems', to='myapp1.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='myapp1.item')),
            ],
        ),
    ]
