# Generated by Django 3.2.4 on 2022-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_client_full_name_client_phoneno_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='numberOfItems',
            field=models.IntegerField(default=1),
        ),
    ]
